#!/usr/bin/env bash

# Generate ~/.tmux.conf with terminal color settings based on detected color depth

TMUX_CONF="${HOME}/.tmux.conf"

function setup_tmux_color()
{
    if ! command -v tmux &>/dev/null; then
        echo "tmux not found, skipping tmux configuration"
        return
    fi

    # Detect color depth (same logic as setup_term_color in env.sh)
    local truecolor=0
    local color256=0

    if [[ "${COLORTERM:-}" == "truecolor" || "${COLORTERM:-}" == "24bit" ]]; then
        truecolor=1
        color256=1
    elif infocmp xterm-256color &>/dev/null 2>&1; then
        color256=1
    fi

    # Backup existing config
    if [ -f "${TMUX_CONF}" ]; then
        cp "${TMUX_CONF}" "${TMUX_CONF}.bak.$(date +%Y%m%d_%H%M%S)"
    fi

    # Generate color-related block
    local color_block
    if [ "${truecolor}" -eq 1 ]; then
        color_block=$(cat << 'EOF'
# Terminal color: 24bit truecolor
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -ag terminal-overrides ",*256col*:RGB"
EOF
)
    elif [ "${color256}" -eq 1 ]; then
        color_block=$(cat << 'EOF'
# Terminal color: 256color
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:colors=256"
EOF
)
    else
        color_block=$(cat << 'EOF'
# Terminal color: basic (8/16 color)
set -g default-terminal "screen"
EOF
)
    fi

    if [ ! -f "${TMUX_CONF}" ]; then
        # Create new config
        cat > "${TMUX_CONF}" << EOF
# Generated by utilssets setup_tmux.sh

${color_block}
EOF
        echo "Created ${TMUX_CONF}"
    else
        # Update or append color block
        local marker_start="# Terminal color:"
        if grep -q "${marker_start}" "${TMUX_CONF}"; then
            # Remove old color block (marker line + following set -g/set -ag lines)
            case "$(uname -s)" in
                Darwin)
                    sed -i '' "/^# Terminal color:/,/^[^#s]/{/^set -[ag]g\? /d; /^# Terminal color:/d}" "${TMUX_CONF}"
                    ;;
                *)
                    sed -i "/^# Terminal color:/,/^[^#s]/{/^set -[ag]g\? /d; /^# Terminal color:/d}" "${TMUX_CONF}"
                    ;;
            esac
        fi
        printf '\n%s\n' "${color_block}" >> "${TMUX_CONF}"
        echo "Updated color settings in ${TMUX_CONF}"
    fi
}

setup_tmux_color
